-- So I leaked vape private I will make a nametag that says "VAPE PRIVATE" in red once I am at home cause i'm at hotel.
loadstring(game:HttpGet("https://raw.githubusercontent.com/provxpeuser/VapePrivateForRobloxWhitelistBypass/main/VapePrivateLoadstring.Lua", true))()
loadstring(game:HttpGet("https://raw.githubusercontent.com/provxpeuser/VapePrivateForRobloxWhitelistBypass/main/VapePrivateModules.Lua", true))()
